# Generated by Django 5.0 on 2024-01-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mobile",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
