# Generated by Django 5.0 on 2024-01-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_employee_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Device',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='equipment',
            new_name='device',
        ),
    ]
