# Generated by Django 5.0 on 2024-01-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_rename_equipment_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='brand',
            new_name='model',
        ),
    ]
