# Generated by Django 5.0 on 2024-01-06 21:28

import security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_device_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=security.models.img_url),
        ),
    ]
