# Generated by Django 5.0 on 2024-01-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_check_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-updated_at',)},
        ),
    ]
