# Generated by Django 5.0 on 2024-01-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_rename_user_type_user_role_user_birthday_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eeu_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
